"""北斗因子挖掘模块 — 合同、点时连接、标签构造、表达式与候选生成。

BF-01: 点时数据与标签合同
BF-02: 因子统计评估器（后续）
BF-03: 表达式 AST 与 Primitive Library
BF-04: 候选生成器（后续）
BF-05: Purged WFO / CPCV / 多重检验（后续）
"""

from .contracts import (
    DatasetManifest,
    HorizonUnit,
    LabelQuality,
    LabelRecord,
    LabelSpec,
    PredictionKey,
    PredictionRecord,
    PriceType,
    ReturnType,
    TimeframeGranularity,
)
from .label_builder import CostEstimate, LabelBuilder, PricePoint
from .point_in_time import (
    BarInfo,
    ClosedBarEnforcer,
    FutureDataGuard,
    IsolationValidator,
    JoinReport,
    PointInTimeJoin,
    PointInTimeJoinResult,
)
from .expression_ast import (
    Add,
    Clip,
    Constant,
    CsRank,
    Diff,
    EMA,
    Eq,
    ExprType,
    Expression,
    ExpressionError,
    ExpressionParseError,
    ExpressionTypeError,
    Feature,
    Ge,
    Gt,
    Lag,
    Le,
    Lt,
    Mul,
    Ne,
    Neg,
    NODE_BY_OP,
    PctChange,
    Residualize,
    RobustZScore,
    RollingMAD,
    RollingMean,
    RollingMedian,
    RollingQuantile,
    RollingStd,
    SafeDiv,
    SignedLog1p,
    SignedSqrt,
    Sub,
    TsRank,
    UnsupportedExpressionError,
    Where,
    ZScore,
    from_dict,
)
from .primitive_library import (
    ALLOWED_OPERATORS,
    FeatureDef,
    PrimitiveRegistry,
    parse_expression,
)

__all__ = [
    # Contracts
    "PredictionKey",
    "PredictionRecord",
    "LabelRecord",
    "LabelSpec",
    "LabelQuality",
    "DatasetManifest",
    "TimeframeGranularity",
    "HorizonUnit",
    "PriceType",
    "ReturnType",
    # PIT Join
    "PointInTimeJoin",
    "PointInTimeJoinResult",
    "JoinReport",
    "ClosedBarEnforcer",
    "BarInfo",
    "FutureDataGuard",
    "IsolationValidator",
    # Labels
    "LabelBuilder",
    "PricePoint",
    "CostEstimate",
    # Expression AST
    "ExprType",
    "Expression",
    "Constant",
    "Feature",
    "Lag",
    "Diff",
    "PctChange",
    "RollingMean",
    "RollingStd",
    "RollingMedian",
    "RollingMAD",
    "RollingQuantile",
    "EMA",
    "TsRank",
    "CsRank",
    "ZScore",
    "RobustZScore",
    "SafeDiv",
    "SignedLog1p",
    "SignedSqrt",
    "Clip",
    "Residualize",
    "Where",
    "Add",
    "Sub",
    "Mul",
    "Neg",
    "Lt",
    "Le",
    "Gt",
    "Ge",
    "Eq",
    "Ne",
    "ExpressionError",
    "ExpressionTypeError",
    "ExpressionParseError",
    "UnsupportedExpressionError",
    "NODE_BY_OP",
    "from_dict",
    # Primitive Library
    "ALLOWED_OPERATORS",
    "FeatureDef",
    "PrimitiveRegistry",
    "parse_expression",
]
