"""北斗因子挖掘模块 — 合同、点时连接、标签构造、表达式与候选生成。

BF-01: 点时数据与标签合同
BF-02: 因子统计评估器（后续）
BF-03: 表达式 AST 与 Primitive Library
BF-04: 候选生成器（后续）
BF-05: Purged WFO / CPCV / 多重检验（后续）
"""

from .contracts import (
    DatasetManifest,
    HorizonUnit,
    LabelQuality,
    LabelRecord,
    LabelSpec,
    PredictionKey,
    PredictionRecord,
    PriceType,
    ReturnType,
    TimeframeGranularity,
)
from .expression_ast import (
    EMA,
    NODE_BY_OP,
    Add,
    Clip,
    Constant,
    CsRank,
    Diff,
    Eq,
    Expression,
    ExpressionError,
    ExpressionParseError,
    ExpressionTypeError,
    ExprType,
    Feature,
    Ge,
    Gt,
    Lag,
    Le,
    Lt,
    Mul,
    Ne,
    Neg,
    PctChange,
    Residualize,
    RobustZScore,
    RollingMAD,
    RollingMean,
    RollingMedian,
    RollingQuantile,
    RollingStd,
    SafeDiv,
    SignedLog1p,
    SignedSqrt,
    Sub,
    TsRank,
    UnsupportedExpressionError,
    Where,
    ZScore,
    from_dict,
)
from .label_builder import CostEstimate, LabelBuilder, PricePoint
from .point_in_time import (
    BarInfo,
    ClosedBarEnforcer,
    FutureDataGuard,
    IsolationValidator,
    JoinReport,
    PointInTimeJoin,
    PointInTimeJoinResult,
)
from .primitive_library import (
    ALLOWED_OPERATORS,
    FeatureDef,
    PrimitiveRegistry,
    parse_expression,
)

__all__ = [
    # Primitive Library
    "ALLOWED_OPERATORS",
    "EMA",
    "NODE_BY_OP",
    "Add",
    "BarInfo",
    "Clip",
    "ClosedBarEnforcer",
    "Constant",
    "CostEstimate",
    "CsRank",
    "DatasetManifest",
    "Diff",
    "Eq",
    # Expression AST
    "ExprType",
    "Expression",
    "ExpressionError",
    "ExpressionParseError",
    "ExpressionTypeError",
    "Feature",
    "FeatureDef",
    "FutureDataGuard",
    "Ge",
    "Gt",
    "HorizonUnit",
    "IsolationValidator",
    "JoinReport",
    # Labels
    "LabelBuilder",
    "LabelQuality",
    "LabelRecord",
    "LabelSpec",
    "Lag",
    "Le",
    "Lt",
    "Mul",
    "Ne",
    "Neg",
    "PctChange",
    # PIT Join
    "PointInTimeJoin",
    "PointInTimeJoinResult",
    # Contracts
    "PredictionKey",
    "PredictionRecord",
    "PricePoint",
    "PriceType",
    "PrimitiveRegistry",
    "Residualize",
    "ReturnType",
    "RobustZScore",
    "RollingMAD",
    "RollingMean",
    "RollingMedian",
    "RollingQuantile",
    "RollingStd",
    "SafeDiv",
    "SignedLog1p",
    "SignedSqrt",
    "Sub",
    "TimeframeGranularity",
    "TsRank",
    "UnsupportedExpressionError",
    "Where",
    "ZScore",
    "from_dict",
    "parse_expression",
]
